snapshot 2025-11-07T15:37:53.473683+00:00

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -478,6 +478,7 @@ d_fd_set=''
 d_fds_bits=''
 d_fdclose=''
 d_fdim=''
+d_fdopendir=''
 d_fegetround=''
 d_ffs=''
 d_ffsl=''
@@ -1051,6 +1052,7 @@ i_quadmath=''
 i_shadow=''
 i_socks=''
 i_stdbool=''
+i_stdckdint=''
 i_stdint=''
 i_stdlib=''
 i_sunmath=''
@@ -7685,6 +7687,9 @@ EOPL
 # of three digit per group separate by '.'s or '_'s. Names are extended
 # with ".0.0" to ensure at least three elements for the pack.
 #                                   -- H.Merijn Brand (m)'06 23-10-2006
+# pack "s>" was introduced in perl-5.10, so I had to rewrite this to an
+# sprintf approach to support bases systems with 5.6.x and 5.8.x
+#                                   -- H.Merijn Brand (m)'25 16-05-2025
 
 my @inc_version_list;
 my @candidates;
@@ -7692,7 +7697,7 @@ my @candidates;
 if (-d $stem) {
     chdir($stem);
     ;@candidates = map {
-	[ $_, pack "s>s>s>", split m/[._]/, "$_.0.0" ] } glob("5.*");
+	[ $_, sprintf "%04d%04d%04d", (split m/[._]/, "$_.0.0")[0,1,2] ] } glob("5.*");
     ;@candidates = sort { $a->[1] cmp $b->[1]} @candidates;
 }
 else {
@@ -7700,7 +7705,7 @@ else {
 }
 
 my ($pversion, $aversion, $vsn5005) = map {
-    pack "s>s>s>", split m/[._]/, "$_.0.0" } $version, $api_versionstring, "5.005";
+    sprintf "%04d%04d%04d", (split m/[._]/, "$_.0.0")[0,1,2] } $version, $api_versionstring, "5.005";
 foreach my $d (@candidates) {
     if ($d->[1] lt $pversion) {
 	if ($d->[1] ge $aversion) {
@@ -14061,6 +14066,10 @@ eval $inlibc
 set fdim d_fdim
 eval $inlibc
 
+: see if fdopendir exists
+set fdopendir d_fdopendir
+eval $inlibc
+
 : see if fegetround exists
 set fegetround d_fegetround
 eval $inlibc
@@ -16754,6 +16763,11 @@ define:define:?*)
 	uvsize=$longsize
 	;;
 esac
+
+if test $ivsize -lt $ptrsize; then
+    echo "Re-run Configure adding -Duse64bitint so as to make integers as large as pointer values" >&4
+    exit 1
+fi
 
 case "$uselongdouble:$d_longdbl" in
 define:define)
@@ -24213,6 +24227,43 @@ $rm_try
 set i_stdbool
 eval $setvar
 
+: see if C23 stdckdint is available
+: we want a real compile instead of Inhdr because some FreeBSD systems
+: have stdckdint.h, but it is not compatible with C++.
+case "$i_stdckdint" in
+'')
+    echo " "
+    $cat >try.c <<EOCP
+#include <stdio.h>
+#include <stdckdint.h>
+int func(long *resultptr, long a, long b)
+{
+    return (ckd_add(resultptr, a, b) ||
+	    ckd_sub(resultptr, a, b) ||
+	    ckd_mul(resultptr, a, b)) ? 1 : 0;
+}
+int main(int argc, char **argv)
+{
+    long result;
+    return func(&result, 42L, 53L);
+}
+EOCP
+    set try
+    if eval $compile; then
+	echo "<stdckdint.h> found." >&4
+	val="$define"
+    else
+	echo "<stdckdint.h> NOT found." >&4
+	val="$undef"
+    fi ;;
+*)
+    val="$i_stdckdint" ;;
+esac
+
+$rm_try
+set i_stdckdint
+eval $setvar
+
 : see if stdint is available
 set stdint.h i_stdint
 eval $inhdr
@@ -25034,6 +25085,7 @@ d_fd_macros='$d_fd_macros'
 d_fd_set='$d_fd_set'
 d_fdclose='$d_fdclose'
 d_fdim='$d_fdim'
+d_fdopendir='$d_fdopendir'
 d_fds_bits='$d_fds_bits'
 d_fegetround='$d_fegetround'
 d_ffs='$d_ffs'
@@ -25622,6 +25674,7 @@ i_sgtty='$i_sgtty'
 i_shadow='$i_shadow'
 i_socks='$i_socks'
 i_stdbool='$i_stdbool'
+i_stdckdint='$i_stdckdint'
 i_stdint='$i_stdint'
 i_stdlib='$i_stdlib'
 i_sunmath='$i_sunmath'
